### ISSUE TITLE
Receiving cannot be started if location is on and GPS or some  other provider is started

### ISSUE THREAD

**Issue by ekigamba** [OpenSRP/android-p2p-sync#38]
The following error occurs:

```
04-16 13:25:04.400 3142-3142/org.smartregister.p2p.sample E/P2pModeSelectInteractor: com.google.android.gms.common.api.ApiException: 17: API: Nearby.CONNECTIONS_API is not available on this device.
        at com.google.android.gms.common.api.internal.zad.zaa(Unknown Source)
        at com.google.android.gms.common.api.internal.zaf.zaa(Unknown Source)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zac(Unknown Source)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.onConnectionFailed(Unknown Source)
        at com.google.android.gms.common.internal.zag.onConnectionFailed(Unknown Source)
        at com.google.android.gms.common.internal.BaseGmsClient$zzf.zza(Unknown Source)
        at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(Unknown Source)
        at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzo(Unknown Source)
        at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(Unknown Source)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at com.google.android.gms.internal.common.zze.dispatchMessage(Unknown Source)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by ekigamba** [comment]
This cannot be easily replicated
